version: '3.8'

services:
  lara:
    image: ghcr.io/l8tenever/lara:latest
    pull_policy: always
    ports:
      - "80:8000"
    volumes:
      - ./uploads:/app/uploads
    restart: always
    depends_on:
      - clamav

  clamav:
    image: clamav/clamav:latest
    restart: always
